<template>
  <div class="learning-dashboard">
    <header class="journal-hero">
      <div class="hero-copy">
        <p class="eyebrow">STUDY DESK · 学业札记</p>
        <h1>把学过的诗，留成一卷自己的山河</h1>
        <p class="hero-subtitle">今日不只是查看数字，而是看看已经走到哪里，下一步该往哪一处风景去。</p>
        <p class="data-note">数据状态 · {{ lastUpdatedTime ? `已更新于 ${lastUpdatedTime}` : '正在读取真实学习记录' }}</p>
      </div>
      <div class="hero-aside">
        <span>卷二 · 今日</span>
        <small>{{ todayLabel }}</small>
        <button type="button" class="refresh-button" :disabled="loading" @click="fetchDashboardData">{{ loading ? '读取中' : '刷新数据' }}</button>
      </div>
      <div class="hero-strokes" aria-hidden="true"><span class="stroke stroke-one"></span><span class="stroke stroke-two"></span><i class="ink-mark ink-mark-one"></i><i class="ink-mark ink-mark-two"></i></div>
    </header>

    <div v-if="loading" class="state-panel"><span class="state-rule"></span><p>正在把今日的学习记录铺开……</p></div>
    <div v-else-if="error" class="state-panel state-panel-error"><span class="state-rule"></span><p>{{ error }}</p><button type="button" class="text-button" @click="fetchDashboardData">再读一次</button></div>

    <main v-else class="journal-body">
      <section class="metric-ledger" aria-label="学习总览">
        <article v-for="metric in headlineMetrics" :key="metric.key" class="metric-item">
          <p>{{ metric.label }}</p><div class="metric-value"><strong>{{ metric.value }}</strong><span>{{ metric.unit }}</span></div><small :class="{ warm: metric.warm }">{{ metric.note }}</small>
        </article>
      </section>

      <section class="journal-section glance-section">
        <div class="section-heading"><div><h2>今日学业</h2><span>AT A GLANCE</span></div><p>用最少的图，回答最重要的学习问题</p></div>
        <div class="glance-grid">
          <article class="paper-panel mastery-panel">
            <div class="panel-heading"><h3>今日掌握度</h3><span>ONE TICK = 1% · 目标 {{ masteryTarget }}%</span></div>
            <div class="tick-donut-wrap"><svg class="tick-donut" viewBox="0 0 220 220" role="img" :aria-label="`综合掌握 ${masteryRate}%`"><g class="tick-ring"><line v-for="tick in 100" :key="`tick-${tick}`" x1="110" y1="20" x2="110" y2="28" :class="{ filled: tick <= masteryRate, target: tick === masteryTarget }" :transform="`rotate(${tick * 3.6} 110 110)`" /></g><circle class="donut-hole" cx="110" cy="110" r="67" /><text class="donut-number" x="110" y="108" text-anchor="middle">{{ masteryRate }}%</text><text class="donut-caption" x="110" y="132" text-anchor="middle">综合掌握</text></svg></div>
            <p class="panel-footnote">{{ masteryFootnote }}</p>
          </article>
          <article class="paper-panel trend-panel">
            <div class="panel-heading"><h3>近 7 日学习轨迹</h3><span>HAIRLINE LINE · 单日最高分</span></div>
            <div v-if="trendHasData" class="line-chart-wrap"><svg class="hairline-chart" viewBox="0 0 520 210" preserveAspectRatio="none" role="img" aria-label="近七日学习轨迹"><g class="chart-guides"><line v-for="guide in [0, 25, 50, 75, 100]" :key="guide" x1="12" x2="508" :y1="trendY(guide)" :y2="trendY(guide)" /></g><polyline class="trend-line" :points="trendPolyline" /><g v-for="(point, index) in trendPoints" :key="`point-${index}`"><circle :cx="point.x" :cy="point.y" r="5" :class="{ empty: !point.score }" /><text class="trend-score" :x="point.x" :y="point.y - 12" text-anchor="middle">{{ point.score || '·' }}</text><text class="trend-date" :x="point.x" y="198" text-anchor="middle">{{ point.label }}</text></g></svg></div>
            <div v-else class="empty-chart">还没有足够的轨迹，完成一次学习后这里会留下墨线。</div><p class="panel-footnote">{{ trendFootnote }}</p>
          </article>
          <article class="paper-panel distribution-panel">
            <div class="panel-heading"><h3>学习方式分布</h3><span>按真实学习行为归类</span></div>
            <div class="distribution-list"><div v-for="row in distributionRows" :key="row.key" class="distribution-row"><div class="distribution-label"><b>{{ row.label }}</b><span>{{ row.percent }}%</span></div><div class="hairline-track"><span :style="{ width: `${row.percent}%` }"></span></div></div></div>
            <p class="panel-footnote">{{ distributionFootnote }}</p>
          </article>
        </div>
      </section>

      <section class="journal-section ability-section">
        <div class="section-heading"><div><h2>能力六面</h2><span>SIX DIMENSIONS</span></div><p>不用雷达图，用统一尺度直接比较强弱</p></div>
        <article class="paper-panel ability-panel"><div v-for="row in abilityRows" :key="row.key" class="ability-row"><div class="ability-label"><b>{{ row.label }}</b><span>{{ row.status }}</span></div><div class="ability-scale" :aria-label="`${row.label} ${row.value} 分`"><span class="scale-mark mark-25"></span><span class="scale-mark mark-50"></span><span class="scale-mark mark-75"></span><i :class="['ability-dot', row.tone]" :style="{ left: `${row.value}%` }"></i></div><strong class="ability-value">{{ row.value }}</strong></div><div class="ability-summary">强项 · {{ abilitySummary.strong }}　·　优先提升 · {{ abilitySummary.focus }}</div></article>
      </section>

      <section class="journal-section rhythm-section">
        <div class="section-heading"><div><h2>七日墨迹</h2><span>WEEKLY RHYTHM</span></div><p>每一格，都是一次真实发生过的学习</p></div>
        <div class="rhythm-grid">
          <article class="paper-panel activity-panel"><div class="panel-heading"><h3>本周学习活跃度</h3><span>ONE CELL = 10 MIN · 颜色深浅表示学习时长</span></div><div class="activity-strip"><div v-for="day in activityDays" :key="day.key" class="activity-day"><span class="activity-date">{{ day.label }}</span><div class="activity-cells"><i v-for="cell in 6" :key="cell" :class="['activity-cell', `level-${Math.min(cell, day.level)}`]"></i></div><small>{{ day.minutes ? `${day.minutes} 分钟` : '未记' }}</small></div></div><p class="panel-footnote">本周共 {{ weekMinutes }} 分钟 · {{ activeDays }} 天有学习记录</p></article>
          <article class="paper-panel advice-panel"><div class="panel-heading"><h3>AI 读书笺</h3><span>根据近 7 日学习行为生成</span></div><div v-if="aiAdviceLoading" class="advice-loading">正在把学习记录写成一段话……</div><template v-else-if="aiAdviceData"><p class="advice-lead">{{ aiAdviceData.summary || '你正在形成稳定的学习节奏。' }}</p><p class="advice-copy">{{ aiAdviceData.strength || '继续保持当前的学习频率，并把一次阅读转成一次主动回忆。' }}</p><p class="advice-copy weak-copy">{{ aiAdviceData.weakness || '下一步可以优先照看尚未完全掌握的篇目。' }}</p><p class="advice-copy">{{ aiAdviceData.suggestion || '今天完成一次背诵复习，再试着用自己的话写下诗中的画面。' }}</p></template><div v-else-if="aiAdviceDisplayed" class="advice-text">{{ aiAdviceDisplayed }}<span v-if="!typewriterDone" class="type-cursor">▍</span></div><div v-else class="advice-fallback"><p class="advice-lead">{{ fallbackLead }}</p><p class="advice-copy">{{ fallbackDetail }}</p></div><div class="advice-actions"><button type="button" class="dark-button" :disabled="aiAdviceLoading" @click="fetchAiAdvice">{{ aiAdviceFull ? '重新生成' : '生成读书笺' }}</button><router-link to="/error-book" class="quiet-link">先看待复习 →</router-link></div><p v-if="aiAdviceError" class="advice-error">{{ aiAdviceError }}</p></article>
        </div>
      </section>

      <section class="journal-section goals-section">
        <div class="section-heading"><div><h2>目标与创作</h2><span>GOALS & CREATION</span></div><p>把数据收束成今天能执行的一步</p></div>
        <div class="goals-grid">
          <article class="paper-panel goals-panel"><div class="panel-heading"><h3>学习目标</h3><span>保持一小步的连续</span></div><div class="goal-line"><div><b>每日学习</b><span>{{ dashboardData.dailyPoemsLearned }} / 3 首</span></div><div class="goal-track"><span :style="{ width: `${dashboardData.dailyGoalProgress}%` }"></span></div></div><div class="goal-line"><div><b>本周学习</b><span>{{ dashboardData.weeklyPoemsLearned }} / 15 首</span></div><div class="goal-track warm-track"><span :style="{ width: `${dashboardData.weeklyGoalProgress}%` }"></span></div></div><p class="panel-footnote">{{ dashboardData.dailyGoalCompleted ? '今日目标已经落笔。' : '今天再完成一次学习，就能让日目标更完整。' }}</p></article>
          <article class="paper-panel creation-panel"><div class="panel-heading"><h3>创作成长</h3><span>从读诗到写诗</span></div><div class="creation-stats"><div><span>作品</span><strong>{{ creationData.total_creations }}</strong><small>篇</small></div><div><span>达标作品</span><strong>{{ creationData.qualified_works }}</strong><small>篇</small></div><div><span>平均分</span><strong>{{ formatCreationAverage(creationData.average_score) }}</strong><small>分</small></div><div><span>最高分</span><strong>{{ creationData.highest_score || 0 }}</strong><small>分</small></div></div><div class="creation-actions"><router-link to="/creation" class="dark-button">开始创作</router-link><router-link to="/creation/records" class="quiet-link">查看作品 →</router-link></div></article>
        </div>
      </section>

      <section class="journal-section recent-section"><div class="section-heading"><div><h2>最近读过</h2><span>RECENT READING</span></div><p>从上次停下的地方继续</p></div><div v-if="dashboardData.recentLearnings.length" class="recent-list"><button v-for="learning in dashboardData.recentLearnings" :key="learning.poem_id" type="button" class="recent-row" @click="navigateToDetail(learning.poem_id)"><span class="recent-index">{{ String(learning.poem_id).padStart(2, '0') }}</span><span class="recent-title"><b>{{ learning.poem_title }}</b><small>{{ learning.poem_author || '未署名' }}</small></span><span class="recent-meta">{{ learning.best_score ? `背诵 ${learning.best_score} 分` : `阅读 ${learning.view_count || 0} 次` }}</span><span class="recent-arrow">↗</span></button></div><div v-else class="recent-empty">你的第一行学习记录会从这里开始。</div></section>
    </main>
    <footer class="journal-footer"><span>「读过的诗，不只留在记忆里，也会慢慢成为你看世界的方式。」</span><b>学习仪表盘 · 视觉重构稿</b></footer>
  </div>
</template>

<script setup>
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import api from '../services/api'

const router = useRouter()
const loading = ref(true)
const error = ref('')
const lastUpdatedTime = ref('')
const refreshTimer = ref(null)
const dashboardData = ref({ totalLearned: 0, averageScore: 0, mistakeCount: 0, recentLearnings: [], masteryRate: 0, streakDays: 0, totalStudyTime: 0, learningTrends: [], dailyGoalCompleted: false, dailyGoalProgress: 0, dailyPoemsLearned: 0, weeklyGoalCompleted: false, weeklyGoalProgress: 0, weeklyPoemsLearned: 0 })
const creationData = ref({ total_creations: 0, qualified_works: 0, average_score: 0, highest_score: 0, last_creation_time: null })
const aiAdviceLoading = ref(false)
const aiAdviceError = ref('')
const aiAdviceFull = ref('')
const aiAdviceDisplayed = ref('')
const aiAdviceData = ref(null)
const typewriterDone = ref(true)
let typeTimer = null

const todayLabel = computed(() => new Intl.DateTimeFormat('zh-CN', { year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date()).replaceAll('/', ' · '))
const masteryRate = computed(() => clamp(dashboardData.value.masteryRate))
const masteryTarget = computed(() => Math.max(70, Math.min(90, masteryRate.value + 8)))
const trends = computed(() => Array.isArray(dashboardData.value.learningTrends) ? dashboardData.value.learningTrends.slice(-7) : [])
const trendHasData = computed(() => trends.value.some(item => Number(item.score) > 0 || Number(item.activePoems) > 0))
const activeDays = computed(() => trends.value.filter(item => Number(item.activePoems) > 0 || Number(item.score) > 0).length)
const weekMinutes = computed(() => trends.value.reduce((sum, item) => sum + Number(item.studyTime || item.duration || 0), 0) || Math.round(Number(dashboardData.value.totalStudyTime || 0) * Math.min(activeDays.value / 7, 1)))

const headlineMetrics = computed(() => { const d = dashboardData.value; return [{ key: 'learned', label: '已学诗词', value: d.totalLearned || 0, unit: '首', note: `累计阅读 ${d.totalLearned || 0} 首` }, { key: 'score', label: '背诵得分', value: Math.round(Number(d.averageScore) || 0), unit: '分', note: '近期开篇表现' }, { key: 'mastery', label: '综合掌握', value: masteryRate.value, unit: '%', note: `目标 ${masteryTarget.value}%` }, { key: 'streak', label: '连续学习', value: d.streakDays || 0, unit: '天', note: d.streakDays ? '保持中的节奏' : '从今天开始' }, { key: 'time', label: '本周时长', value: formatDuration(d.totalStudyTime), unit: '', note: '记录中的学习时长' }, { key: 'review', label: '待复习', value: d.mistakeCount || 0, unit: '处', note: d.mistakeCount ? '建议优先回看' : '暂时没有积压', warm: Boolean(d.mistakeCount) }] })
const masteryFootnote = computed(() => masteryRate.value >= masteryTarget.value ? '已越过本阶段目标，继续保持主动回忆。' : `距离本阶段目标还差 ${Math.max(masteryTarget.value - masteryRate.value, 0)} 个百分点。`)
const trendFootnote = computed(() => trendHasData.value ? '线条的起伏对应真实记录，空白日不被补成好看的数字。' : '完成一次学习后，这里会显示真实轨迹。')
const trendPoints = computed(() => { const source = trends.value.length ? trends.value : Array.from({ length: 7 }, () => ({ date: '', score: 0, activePoems: 0 })); const step = 496 / Math.max(source.length - 1, 1); return source.map((item, index) => ({ x: 12 + index * step, y: trendY(Number(item.score) || 0), score: Math.round(Number(item.score) || 0), label: item.date || '·' })) })
const trendPolyline = computed(() => trendPoints.value.map(point => `${point.x},${point.y}`).join(' '))

const distributionRows = computed(() => { const records = dashboardData.value.recentLearnings || []; const totals = records.reduce((result, item) => { result.read += Number(item.view_count) || 0; result.explain += Number(item.ai_explain_count) || 0; result.recite += Number(item.recite_attempts) || 0; return result }, { read: 0, explain: 0, recite: 0 }); const total = totals.read + totals.explain + totals.recite; return [{ key: 'read', label: '查看学习', percent: total ? Math.round(totals.read / total * 100) : 0 }, { key: 'explain', label: 'AI 讲解', percent: total ? Math.round(totals.explain / total * 100) : 0 }, { key: 'recite', label: '背诵练习', percent: total ? Math.round(totals.recite / total * 100) : 0 }] })
const distributionFootnote = computed(() => distributionRows.value.some(row => row.percent) ? '分布由最近学习记录中的真实行为次数归类。' : '开始阅读、讲解或背诵后，这里会出现行为分布。')

const abilityValues = computed(() => { const d = dashboardData.value; const recent = d.recentLearnings || []; const understanding = recent.length ? Math.round(recent.reduce((sum, item) => { const views = Math.max(Number(item.view_count) || 1, 1); return sum + Math.min(1, (Number(item.ai_explain_count) || 0) / views) }, 0) / recent.length * 100) : Math.round(masteryRate.value * 0.7); const memory = Math.min(100, Math.round((Number(d.totalLearned) || 0) / 20 * 100)); const persistence = trends.value.length ? Math.round(activeDays.value / trends.value.length * 100) : 0; const application = d.totalLearned ? Math.max(0, Math.round((1 - Math.min(Number(d.mistakeCount) || 0, Number(d.totalLearned)) / Number(d.totalLearned)) * 100)) : 0; const creation = Number(creationData.value.total_creations) ? Math.round(Math.min(100, Number(creationData.value.average_score) || Number(creationData.value.highest_score) || 0)) : 0; return [clamp(d.averageScore), clamp(understanding), memory, persistence, application, creation] })
const abilityRows = computed(() => ['背诵', '理解', '记忆', '坚持', '应用', '创作'].map((label, index) => { const value = abilityValues.value[index]; return { key: label, label, value, status: value >= 80 ? '熟练' : value >= 60 ? '稳定' : value ? '需巩固' : '待积累', tone: value >= 80 ? 'strong' : value < 60 ? 'focus' : 'steady' } }))
const abilitySummary = computed(() => { const sorted = [...abilityRows.value].sort((a, b) => b.value - a.value); return { strong: sorted.slice(0, 2).map(row => row.label).join('、') || '暂无', focus: sorted.slice(-2).map(row => row.label).join('、') || '暂无' } })
const activityDays = computed(() => { const source = trends.value.length ? trends.value : Array.from({ length: 7 }, () => ({ date: '', activePoems: 0, score: 0 })); return source.map((item, index) => { const minutes = Number(item.studyTime || item.duration || 0) || (Number(item.activePoems) ? Math.max(10, Number(item.activePoems) * 10) : 0); return { key: `${item.date || 'empty'}-${index}`, label: item.date || '·', minutes, level: minutes ? Math.max(1, Math.min(6, Math.ceil(minutes / 10))) : 0 } }) })
const fallbackLead = computed(() => dashboardData.value.totalLearned ? '你已经在形成稳定的学习节奏。' : '先从今天的一首诗开始。')
const fallbackDetail = computed(() => dashboardData.value.mistakeCount ? `当前有 ${dashboardData.value.mistakeCount} 处内容值得回看，先做一次主动回忆，再打开原文核对。` : '读一遍，合上页面背一遍，再写下一个你真正记住的画面。')

function clamp(value) { return Math.max(0, Math.min(100, Math.round(Number(value) || 0))) }
function trendY(score) { return 170 - clamp(score) * 1.35 }
function formatDuration(minutes) { const total = Math.max(0, Math.round(Number(minutes) || 0)); if (total < 60) return `${total}分`; return `${Math.floor(total / 60)}时${total % 60 ? `${total % 60}分` : ''}` }
function formatCreationAverage(value) { return Number.isFinite(Number(value)) ? Number(value).toFixed(1) : '0.0' }
function navigateToDetail(poemId) { router.push(`/poem/${poemId}`) }
function runTypewriter(text) { clearInterval(typeTimer); aiAdviceDisplayed.value = ''; typewriterDone.value = false; let index = 0; typeTimer = setInterval(() => { if (index >= text.length) { clearInterval(typeTimer); typewriterDone.value = true; return } aiAdviceDisplayed.value += text.slice(index, index + 2); index += 2 }, 18) }
async function fetchAiAdvice() { clearInterval(typeTimer); aiAdviceLoading.value = true; aiAdviceError.value = ''; aiAdviceFull.value = ''; aiAdviceData.value = null; aiAdviceDisplayed.value = ''; try { const response = await api.learn.aiSuggestions(); const content = response.data?.content; if (content && typeof content === 'object') { aiAdviceData.value = content; aiAdviceFull.value = 'loaded' } else if (content) { aiAdviceFull.value = String(content); runTypewriter(String(content)) } else throw new Error(response.message || '暂时没有生成内容') } catch (err) { aiAdviceError.value = err.message || 'AI 读书笺暂时没有生成成功，先使用本地提示。' } finally { aiAdviceLoading.value = false } }

function normalizeDashboardData(data) { const list = Array.isArray(data.recentLearnings) ? data.recentLearnings : []; const trendList = Array.isArray(data.learningTrends) ? data.learningTrends : []; const today = trendList[trendList.length - 1] || {}; const dayCount = Number(today.activePoems) || 0; const weekCount = trendList.reduce((sum, item) => sum + (Number(item.activePoems) || 0), 0); let streak = 0; for (let index = trendList.length - 1; index >= 0; index -= 1) { if (Number(trendList[index].activePoems) > 0 || Number(trendList[index].score) > 0) streak += 1; else break } return { ...dashboardData.value, ...data, recentLearnings: list, learningTrends: trendList, streakDays: data.streakDays ?? streak, totalStudyTime: Number(data.totalStudyTime) || 0, dailyPoemsLearned: dayCount, dailyGoalProgress: Math.min(100, Math.round(dayCount / 3 * 100)), dailyGoalCompleted: dayCount >= 3, weeklyPoemsLearned: weekCount, weeklyGoalProgress: Math.min(100, Math.round(weekCount / 15 * 100)), weeklyGoalCompleted: weekCount >= 15 } }
function useEmptyData() { dashboardData.value = normalizeDashboardData({ totalLearned: 0, averageScore: 0, mistakeCount: 0, masteryRate: 0, totalStudyTime: 0, recentLearnings: [], learningTrends: [] }) }
async function fetchDashboardData() { loading.value = true; error.value = ''; try { const response = await api.learn.dashboard(); dashboardData.value = normalizeDashboardData(response.data || {}); try { const creation = await api.creationWorkbench.getStats(); if (creation.success && creation.data) creationData.value = { ...creationData.value, ...creation.data } } catch (creationError) { console.warn('获取创作成长数据失败:', creationError) } if (!aiAdviceFull.value && !aiAdviceData.value) fetchAiAdvice() } catch (err) { console.error('获取仪表盘数据失败:', err); useEmptyData(); error.value = '暂时没有读到学习数据，请检查服务连接后再试。' } finally { loading.value = false; lastUpdatedTime.value = new Date().toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' }) } }
onMounted(() => { fetchDashboardData(); refreshTimer.value = setInterval(fetchDashboardData, 30000) })
onUnmounted(() => { if (refreshTimer.value) clearInterval(refreshTimer.value); clearInterval(typeTimer) })
</script>

<style scoped>
.learning-dashboard { --paper: #f6f8f3; --ink: #153e38; --ink-soft: #456760; --muted: #758b85; --faint: #b8cbc4; --line: #d4e2dc; --jade: #5c9c8e; --jade-deep: #2c7166; --warm: #b86b3f; width: 100%; min-height: calc(100dvh - 84px); padding: 52px clamp(28px, 4vw, 72px) 26px; color: var(--ink); background: radial-gradient(circle at 9% 4%, rgba(194, 224, 210, .55), transparent 26%), radial-gradient(circle at 91% 48%, rgba(210, 222, 198, .34), transparent 25%), linear-gradient(125deg, rgba(248, 250, 246, .97), rgba(239, 246, 240, .88)); border: 0 !important; border-radius: 0 !important; overflow: hidden; font-family: 'Noto Sans SC', 'Microsoft YaHei', sans-serif; }
.journal-hero, .journal-body, .journal-footer { width: 100%; max-width: none; margin: 0; }
.journal-hero { min-height: 262px; display: grid; grid-template-columns: 1fr auto; gap: 48px; align-items: end; position: relative; padding: 8px 0 44px; border-bottom: 1px solid var(--ink); }
.hero-copy { position: relative; z-index: 1; max-width: 850px; }.eyebrow { margin-bottom: 24px; color: var(--warm); font-size: 12px; font-weight: 700; letter-spacing: .11em; }.learning-dashboard h1, .learning-dashboard h2, .learning-dashboard h3 { color: var(--ink); }.journal-hero h1 { max-width: 870px; margin: 0; font-family: 'Noto Serif SC', 'Songti SC', serif; font-size: clamp(40px, 5.1vw, 78px); font-weight: 600; letter-spacing: -.06em; line-height: 1.08; }.hero-subtitle { max-width: 690px; margin: 5px 0 14px; color: var(--ink-soft); font-size: 17px; line-height: 1.7; }.data-note { color: var(--muted); font-size: 12px; }
.hero-aside { display: flex; flex-direction: column; align-items: flex-end; gap: 5px; padding-bottom: 7px; color: var(--ink-soft); font-family: 'Noto Serif SC', serif; font-size: 15px; white-space: nowrap; }.hero-aside small { color: var(--muted); font-family: 'Noto Sans SC', sans-serif; font-size: 11px; letter-spacing: .08em; }.refresh-button { margin-top: 34px; padding: 11px 22px; color: var(--jade-deep); background: rgba(228, 243, 237, .85); border: 1px solid #c5e2d8; border-radius: 12px; font: 600 13px 'Noto Sans SC', sans-serif; cursor: pointer; transition: transform .25s ease, background .25s ease; }.refresh-button:hover:not(:disabled) { transform: translateY(-2px); background: #e0f0e9; }.refresh-button:disabled { opacity: .6; cursor: wait; }.hero-strokes { position: absolute; right: 2%; top: 25px; width: 39%; height: 118px; opacity: .85; pointer-events: none; }.stroke { position: absolute; right: 0; width: 100%; height: 42px; border-top: 2px solid rgba(175, 211, 202, .45); border-radius: 50%; transform: rotate(4deg); }.stroke-one { top: 24px; }.stroke-two { top: 56px; width: 86%; border-color: rgba(183, 204, 182, .48); transform: rotate(-3deg); }.ink-mark { position: absolute; display: block; width: 18px; height: 11px; border-radius: 60% 40% 58% 42%; background: var(--warm); transform: rotate(-42deg); }.ink-mark-one { top: 18px; left: 15%; }.ink-mark-two { right: 28%; bottom: 19px; width: 17px; background: #df8b90; transform: rotate(-35deg); }
.metric-ledger { display: grid; grid-template-columns: repeat(6, 1fr); margin: 30px 0 74px; border-top: 1px solid var(--line); border-bottom: 1px solid var(--line); }.metric-item { min-height: 118px; padding: 22px 20px 18px; border-right: 1px solid var(--line); }.metric-item:last-child { border-right: 0; }.metric-item p { margin-bottom: 8px; color: var(--muted); font-size: 13px; font-weight: 600; }.metric-value { display: flex; align-items: baseline; gap: 7px; white-space: nowrap; }.metric-value strong { color: var(--ink); font: 700 clamp(25px, 2.3vw, 37px) 'Noto Sans SC', sans-serif; letter-spacing: -.05em; font-variant-numeric: tabular-nums; }.metric-value span { color: var(--muted); font-size: 12px; }.metric-item small { display: block; margin-top: 7px; color: var(--muted); font-size: 11px; }.metric-item small::before { content: ''; display: inline-block; width: 6px; height: 6px; margin-right: 7px; border-radius: 50%; background: var(--jade); }.metric-item small.warm::before { background: var(--warm); }
.journal-section { margin-bottom: 78px; }.section-heading { display: flex; justify-content: space-between; align-items: end; gap: 24px; padding-bottom: 15px; border-bottom: 1px solid var(--line); }.section-heading h2 { margin: 0; font: 600 clamp(28px, 3vw, 40px) 'Noto Serif SC', 'Songti SC', serif; letter-spacing: -.04em; line-height: 1.1; }.section-heading span { display: block; margin-top: 4px; color: var(--muted); font-size: 11px; font-weight: 700; letter-spacing: .11em; }.section-heading > p { margin: 0 0 5px; color: var(--muted); font-size: 13px; }.glance-grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 20px; padding-top: 22px; }.paper-panel { position: relative; overflow: hidden; padding: 28px; background: rgba(251, 252, 249, .76); border: 1px solid var(--line); border-radius: 17px; box-shadow: inset 0 1px 0 rgba(255,255,255,.9); }.paper-panel::after { content: ''; position: absolute; right: 18px; top: 18px; width: 20px; height: 8px; border-radius: 60%; background: rgba(110, 163, 148, .22); transform: rotate(-42deg); pointer-events: none; }.panel-heading { position: relative; z-index: 1; display: flex; flex-direction: column; gap: 4px; }.panel-heading h3 { margin: 0; font: 600 23px 'Noto Serif SC', 'Songti SC', serif; letter-spacing: -.03em; }.panel-heading span { color: var(--muted); font-size: 10px; font-weight: 700; letter-spacing: .06em; }.panel-footnote { margin: 22px 0 0; color: var(--muted); font-size: 12px; line-height: 1.6; }
.mastery-panel, .trend-panel, .distribution-panel { min-height: 360px; }.tick-donut-wrap { display: grid; place-items: center; padding: 20px 0 4px; }.tick-donut { width: 218px; height: 218px; overflow: visible; }.tick-ring line { stroke: #dbe6e1; stroke-width: 5; stroke-linecap: butt; }.tick-ring line.filled { stroke: var(--jade); }.tick-ring line.target { stroke: var(--warm); stroke-width: 7; }.donut-hole { fill: #f8faf6; stroke: #e5eee9; stroke-width: 1; }.donut-number { fill: var(--ink); font: 700 32px 'Noto Sans SC', sans-serif; letter-spacing: -.05em; }.donut-caption { fill: var(--muted); font: 12px 'Noto Sans SC', sans-serif; }
.line-chart-wrap { height: 215px; margin-top: 14px; }.hairline-chart { width: 100%; height: 100%; overflow: visible; }.chart-guides line { stroke: #dce7e1; stroke-width: 1; }.trend-line { fill: none; stroke: var(--ink); stroke-width: 1.7; stroke-linecap: round; stroke-linejoin: round; }.hairline-chart circle { fill: var(--jade); stroke: var(--ink); stroke-width: 1.5; }.hairline-chart circle.empty { fill: #e3ebe7; stroke: #c8d8d1; }.trend-score { fill: var(--ink); font: 600 11px 'Noto Sans SC', sans-serif; }.trend-date { fill: var(--muted); font: 10px 'Noto Sans SC', sans-serif; }.empty-chart { display: grid; place-items: center; height: 215px; margin-top: 14px; color: var(--muted); font-size: 13px; text-align: center; }
.distribution-list { display: grid; gap: 24px; margin-top: 52px; }.distribution-label { display: flex; justify-content: space-between; margin-bottom: 8px; color: var(--ink); font-size: 13px; }.distribution-label b { font-weight: 600; }.distribution-label span { color: var(--muted); font-variant-numeric: tabular-nums; }.hairline-track { height: 9px; background: #e1e9e5; overflow: hidden; }.hairline-track span { display: block; height: 100%; background: var(--jade); transition: width .8s cubic-bezier(.16,1,.3,1); }.distribution-row:nth-child(2) .hairline-track span { background: #79ae9f; }.distribution-row:nth-child(3) .hairline-track span { background: var(--warm); }
.ability-panel { margin-top: 22px; padding: 30px 42px 24px; }.ability-row { display: grid; grid-template-columns: 190px 1fr 40px; align-items: center; gap: 28px; min-height: 48px; }.ability-label { display: flex; align-items: baseline; gap: 14px; }.ability-label b { min-width: 42px; font: 600 17px 'Noto Serif SC', serif; }.ability-label span { color: var(--muted); font-size: 11px; }.ability-scale { position: relative; height: 20px; border-top: 1px solid #bfd3cb; border-bottom: 1px solid #bfd3cb; background: repeating-linear-gradient(90deg, transparent 0, transparent calc(10% - 1px), #c5d9d1 calc(10% - 1px), #c5d9d1 10%); }.scale-mark { position: absolute; top: -6px; width: 1px; height: 12px; background: #aac6bb; }.mark-25 { left: 25%; }.mark-50 { left: 50%; }.mark-75 { left: 75%; }.ability-dot { position: absolute; top: 50%; width: 15px; height: 15px; border: 2px solid var(--paper); border-radius: 50%; background: var(--jade); transform: translate(-50%, -50%); box-shadow: 0 0 0 1px var(--jade); }.ability-dot.strong { background: var(--jade-deep); box-shadow: 0 0 0 1px var(--jade-deep); }.ability-dot.focus { background: var(--warm); box-shadow: 0 0 0 1px var(--warm); }.ability-value { font: 700 16px 'Noto Sans SC', sans-serif; text-align: right; font-variant-numeric: tabular-nums; }.ability-summary { margin-top: 19px; color: var(--muted); font-size: 12px; text-align: right; }
.rhythm-grid, .goals-grid { display: grid; grid-template-columns: 1.25fr .9fr; gap: 20px; padding-top: 22px; }.activity-panel, .advice-panel { min-height: 308px; }.activity-strip { display: grid; grid-template-columns: repeat(7, 1fr); gap: 16px; margin-top: 30px; }.activity-day { display: grid; gap: 8px; justify-items: center; min-width: 0; }.activity-date { color: var(--muted); font-size: 10px; letter-spacing: .03em; }.activity-cells { display: grid; gap: 5px; width: 100%; }.activity-cell { height: 12px; border-radius: 4px; background: #e3ebe7; }.activity-cell.level-1 { background: #d6e7e0; }.activity-cell.level-2 { background: #b7d5ca; }.activity-cell.level-3 { background: #94c2b2; }.activity-cell.level-4 { background: #72ae9d; }.activity-cell.level-5 { background: #4d9482; }.activity-cell.level-6 { background: var(--ink); }.activity-day small { color: var(--muted); font-size: 10px; white-space: nowrap; }.advice-panel { background: rgba(233, 244, 239, .82); }.advice-panel::before { content: ''; position: absolute; left: 31px; top: 88px; bottom: 55px; width: 2px; background: var(--jade); }.advice-panel .panel-heading, .advice-panel > p, .advice-panel > div:not(.panel-heading) { margin-left: 28px; }.advice-lead { margin-top: 34px; font: 600 21px/1.55 'Noto Serif SC', serif; }.advice-copy { margin-top: 12px; color: var(--ink-soft); font-size: 13px; line-height: 1.8; }.weak-copy { color: #6e5c4e; }.advice-text { margin-top: 34px; color: var(--ink-soft); font: 15px/1.9 'Noto Serif SC', serif; white-space: pre-wrap; }.advice-fallback { margin-top: 34px; }.advice-loading { margin-top: 34px; color: var(--muted); font-size: 13px; }.type-cursor { color: var(--warm); animation: blink 1s steps(2, start) infinite; }@keyframes blink { 50% { opacity: 0; } }.advice-actions { display: flex; align-items: center; gap: 18px; margin-top: 20px; }.dark-button { display: inline-flex; align-items: center; justify-content: center; min-height: 40px; padding: 0 22px; color: #f8fbf8; background: var(--ink); border: 1px solid var(--ink); border-radius: 10px; font: 600 12px 'Noto Sans SC', sans-serif; text-decoration: none; cursor: pointer; transition: transform .25s ease, background .25s ease; }.dark-button:hover:not(:disabled) { transform: translateY(-2px); background: #24594f; }.dark-button:disabled { opacity: .55; cursor: wait; }.quiet-link, .text-button { color: var(--jade-deep); background: transparent; border: 0; font: 600 12px 'Noto Sans SC', sans-serif; text-decoration: none; cursor: pointer; }.quiet-link:hover, .text-button:hover { color: var(--warm); }.advice-error { margin-top: 12px; color: var(--warm); font-size: 11px; }
.goal-line { margin-top: 29px; }.goal-line + .goal-line { margin-top: 25px; }.goal-line > div:first-child { display: flex; justify-content: space-between; margin-bottom: 9px; font-size: 12px; }.goal-line b { font-weight: 600; }.goal-line span { color: var(--muted); }.goal-track { height: 9px; background: #dfe9e4; overflow: hidden; }.goal-track > span { display: block; height: 100%; background: var(--jade); }.warm-track > span { background: #ba8a4b; }.creation-stats { display: grid; grid-template-columns: repeat(2, 1fr); gap: 22px 32px; margin-top: 30px; }.creation-stats div { display: grid; grid-template-columns: auto 1fr; column-gap: 7px; align-items: baseline; }.creation-stats span { grid-column: 1 / -1; color: var(--muted); font-size: 11px; }.creation-stats strong { font: 700 27px 'Noto Sans SC', sans-serif; letter-spacing: -.04em; }.creation-stats small { color: var(--muted); font-size: 11px; }.creation-actions { display: flex; align-items: center; gap: 18px; margin-top: 26px; }
.recent-section { margin-bottom: 22px; }.recent-list { margin-top: 8px; border-bottom: 1px solid var(--line); }.recent-row { display: grid; grid-template-columns: 48px minmax(0, 1fr) auto 22px; align-items: center; gap: 15px; width: 100%; padding: 16px 8px; color: var(--ink); background: transparent; border: 0; border-top: 1px solid var(--line); text-align: left; cursor: pointer; transition: background .2s ease, padding .2s ease; }.recent-row:hover { padding-left: 15px; background: rgba(233, 244, 239, .62); }.recent-index { color: var(--faint); font: 12px 'Noto Sans SC', sans-serif; }.recent-title { display: flex; align-items: baseline; gap: 14px; min-width: 0; }.recent-title b { font: 600 17px 'Noto Serif SC', serif; }.recent-title small, .recent-meta { color: var(--muted); font-size: 12px; }.recent-arrow { color: var(--jade-deep); font-size: 16px; }.recent-empty { padding: 28px 0; color: var(--muted); font-size: 13px; border-bottom: 1px solid var(--line); }.journal-footer { display: flex; justify-content: space-between; gap: 24px; margin-top: 22px; padding: 25px 6px 8px; color: var(--muted); border-top: 1px solid var(--ink); font: 12px 'Noto Serif SC', serif; }.journal-footer b { font-family: 'Noto Sans SC', sans-serif; font-size: 11px; font-weight: 600; }
.state-panel { display: grid; place-items: center; min-height: 380px; color: var(--muted); font-size: 14px; }.state-rule { width: 42px; height: 1px; margin-bottom: 15px; background: var(--jade); }.state-panel-error { color: var(--warm); }.state-panel-error .text-button { margin-top: 12px; }
@media (max-width: 1100px) { .metric-ledger { grid-template-columns: repeat(3, 1fr); }.metric-item:nth-child(3) { border-right: 0; }.metric-item:nth-child(n + 4) { border-top: 1px solid var(--line); }.glance-grid { grid-template-columns: repeat(2, 1fr); }.distribution-panel { grid-column: span 2; min-height: 300px; }.distribution-list { grid-template-columns: repeat(3, 1fr); margin-top: 40px; } }
@media (max-width: 760px) { .learning-dashboard { min-height: calc(100dvh - 72px); padding: 30px 14px 20px; }.journal-hero { min-height: 0; grid-template-columns: 1fr; gap: 25px; padding-bottom: 30px; }.journal-hero h1 { font-size: clamp(34px, 10vw, 52px); }.hero-subtitle { font-size: 15px; }.hero-aside { align-items: flex-start; }.refresh-button { margin-top: 10px; }.hero-strokes { top: 50px; width: 48%; opacity: .5; }.metric-ledger { grid-template-columns: repeat(2, 1fr); margin: 24px 0 52px; }.metric-item { padding: 16px 12px; }.metric-item:nth-child(odd) { border-right: 1px solid var(--line); }.metric-item:nth-child(even) { border-right: 0; }.metric-item:nth-child(n + 3) { border-top: 1px solid var(--line); }.section-heading { display: block; }.section-heading > p { margin-top: 12px; }.journal-section { margin-bottom: 56px; }.glance-grid, .rhythm-grid, .goals-grid { grid-template-columns: 1fr; }.distribution-panel { grid-column: auto; }.distribution-list { grid-template-columns: 1fr; gap: 18px; margin-top: 30px; }.paper-panel { padding: 23px 20px; }.mastery-panel, .trend-panel, .distribution-panel, .activity-panel, .advice-panel { min-height: 0; }.ability-panel { padding: 22px 17px; overflow-x: auto; }.ability-row { grid-template-columns: 104px minmax(210px, 1fr) 30px; gap: 13px; }.ability-label { display: block; }.ability-label b { display: block; }.ability-label span { display: block; margin-top: 2px; }.ability-summary { text-align: left; white-space: nowrap; }.activity-strip { gap: 7px; }.activity-date { font-size: 9px; }.activity-day small { font-size: 9px; }.advice-panel::before { left: 23px; }.advice-panel .panel-heading, .advice-panel > p, .advice-panel > div:not(.panel-heading) { margin-left: 20px; }.advice-actions { flex-wrap: wrap; }.recent-row { grid-template-columns: 32px minmax(0, 1fr) 18px; gap: 10px; }.recent-meta { display: none; }.recent-title { display: block; }.recent-title small { display: block; margin-top: 3px; }.journal-footer { display: block; line-height: 1.8; }.journal-footer b { display: block; margin-top: 8px; } }
@media (prefers-reduced-motion: reduce) { .refresh-button, .dark-button, .quiet-link, .recent-row, .hairline-track span { transition: none; }.type-cursor { animation: none; } }
</style>
